eight_points_guzzle:
    logging: "%kernel.debug%"

    clients:
        commons:
            base_url: "https://commons.wikimedia.org/w/api.php"

            # guzzle client options (full description here: https://guzzle.readthedocs.org/en/latest/request-options.html)
            options:
                headers:
                    Accept: "application/json"
                timeout: 30
