monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            event_processor:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/event_processor.log'
                channels: [ event_processor ]
            main:
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug
                channels: [ '!event' ]
            console:
                type: console
                process_psr_3_messages: false
                channels: [ '!event', '!doctrine', '!console' ]
            # To follow logs in real time, execute the following command:
            # `bin/console server:log -vv`
            server_log:
                type: server_log
                process_psr_3_messages: false
                host: 127.0.0.1:9911

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            event_processor:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/event_processor.log'
                channels: [ event_processor ]
            main:
                type: fingers_crossed
                action_level: critical
                handler: main_handler
            main_handler:
                type: group
                members: [ console, log_file, mailer ]
            console:
                type: console
                level: debug
                process_psr_3_messages: false
            log_file:
                type: stream
                level: info
                path: '%kernel.logs_dir%/%kernel.environment%.log'
            mailer:
                type: deduplication
                handler: symfony_mailer
            symfony_mailer:
                type: symfony_mailer
                level: critical
                from_email: '%env(MAILER_FROM_EMAIL)%'
                to_email: '%env(MAILER_TO_EMAIL)%'
                subject: 'Event Metrics error: %%message%%'
                formatter: monolog.formatter.html
                content_type: text/html
