twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:      ['bootstrap_3_layout.html.twig']
    globals:
        site_notice_style:   '%env(APP_NOTICE_STYLE)%'
        site_notice_text:    '%env(APP_NOTICE_TEXT)%'
