version: "2"        # required to adjust maintainability checks
checks:
    argument-count:
        config:
            threshold: 6
    complex-logic:
        config:
            threshold: 4
    file-lines:
        config:
            threshold: 500
    method-complexity:
        config:
            threshold: 20
    method-count:
        config:
            threshold: 40
    method-lines:
        config:
            threshold: 80
    nested-control-flow:
        config:
            threshold: 4
    return-statements:
        config:
            threshold: 5
    similar-code:
        config:
            threshold: # language-specific defaults. an override will affect all languages.
    identical-code:
        config:
            threshold: # language-specific defaults. an override will affect all languages.
exclude_patterns:
    - "var/"
    - "app/DoctrineMigrations/"
    - "tests/"
    - "app/Resources/assets/vendor/"
    - "src/AppBundle/AppBundle.php"
