build:
    environment:
        php:
            version: 7.2
    dependencies:
        override:
            # Disable the inferred commands.
            - true
        before:
            # Install the minimum in order to have dependency classes loaded for inspection.
            - composer install --no-scripts
    tests:
        override:
            # Disables tests. We're only using Scrutinizer for inspections.
            command: 'php -v'

filter:
    excluded_paths:
        - 'var/*'
        - 'src/App*'
        - 'src/DoctrineMigrations'
        - 'tests/*'
        - 'bin/*'
        - '*.min.js'
    dependency_paths:
        - 'vendor/*'

build_failure_conditions:
    - 'patches.label("Doc Comments").exists'       # No doc comments patches allowed
    - 'patches.label("Spacing").new.count > 1'     # More than 1 new spacing patch

    - 'issues.label("coding-style").new.count > 5' # More than 5 new coding style issues.
    - 'issues.severity(>= MAJOR).new.exists'       # New issues of major or higher severity

    - 'project.metric("scrutinizer.quality", < 8)' # Code Quality Rating drops below 9
