build:
    environment:
        php:
            version: 5.6
        ruby: 2.4.0
    tests:
        override:
            -
                command: vendor/bin/simple-phpunit --coverage-clover=coverage.xml
                coverage:
                    file: coverage.xml
                    format: php-clover
filter:
    excluded_paths:
        - 'var/*'
        - 'app/*'
        - 'tests/*'
        - 'bin/*'
        - 'vendor/*'
        - '*.min.js'

build_failure_conditions:
    - 'elements.rating(<= C).exists'               # No classes/methods with a rating of C or worse

    - 'patches.label("Doc Comments").exists'       # No doc comments patches allowed
    - 'patches.label("Spacing").new.count > 1'     # More than 1 new spacing patch

    - 'issues.label("coding-style").new.count > 5' # More than 5 new coding style issues.
    - 'issues.severity(>= MAJOR).new.exists'       # New issues of major or higher severity

    - 'project.metric("scrutinizer.quality", < 9)' # Code Quality Rating drops below 9
    # - 'project.metric("scrutinizer.test_coverage", < 0.80)' # Code Coverage drops below 80%

    # # Code Coverage decreased from previous inspection
    # - 'project.metric_change("scrutinizer.test_coverage", < 0)'
