imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        connections:
            eventmetrics:
                driver:   pdo_mysql
                host:     localhost
                port:     "%database.test.port%"
                dbname:   "%database.test.name%"
                user:     "%database.test.user%"
                password: "%database.test.password%"
