imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        event_processor:
            level: debug
            type: stream
            path: '%kernel.logs_dir%/event_processor.log'
            channels: [event_processor]
        main:
            type: fingers_crossed
            action_level: critical
            handler: main_handler
        main_handler:
            type: group
            members: [console, log_file, mailer]
        console:
            type: console
            level: debug
            process_psr_3_messages: false
        log_file:
            type: stream
            level: info
            path: '%kernel.logs_dir%/%kernel.environment%.log'
        mailer:
            type: deduplication
            handler: swift
        swift:
            type: swift_mailer
            level: critical
            from_email: '%mailer.from_email%'
            to_email: '%mailer.to_email%'
            subject: 'EventMetrics error: %%message%%'
            formatter: monolog.formatter.html
            content_type: text/html
